version: "3.8"

services:
  db:
    container_name: bookApp_postgres_container
    image: "postgres:14.5"
    environment:
      POSTGRES_USER: random
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "put db"
      PGDATA: "put location"
    ports:
      - 5432:5432
    networks:
      - book_app_network
    restart: unless-stoped
    healthcheck:
      test: ["CMD", "pg_isready -U chatAppUser"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:'{{db.PGDATA}}'
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    networks:
      - book_app_network
    environment:
      PGADMIN_DEFAULT_EMAIL: "{{db.PGADMIN_DEFAULT_EMAIL}}"
      PGADMIN_DEFAULT_PASSWORD: "{{db.PGADMIN_DEFAULT_PASSWORD}}"
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
